In [ ]:
data = [
    ("В дис?","го"),
    ("Влад, ты сегодня работаешь?","Нет, А че"),
    ("Да думал может в дис?", "Так го"),
    ("Ну сейчас помоюсь, еду погрею и буду","Ну го бырее"),
    ("Влад не хочешь в дис через 5 мин?","Го"),
    ("пойдём играть?", "Пошлмь"),
    ("Влад, ты когда домой?","До конца смены 3 часа. Я щас нанесу материальный ущерб в лям рублей, сук как же хочеться спать"),
    ("А кто-то вчера вечером говорил покушает и спать","Так а я чё сделал"),
    ("Го в желике в бк работать, может с той тянкой познакомишься","Не надо давать мне надежды..."),
    ("Влад, ты мне про давинчик написал, и теперь он мне написывает, мне страшно","Бойся женщин"),
    ("А", "Можно когда нибудь мы устроимся вмести в бургер кинг или мак?"),
    ("Ну хз","Да бля("),
    ("А что?","Да завод заводом, А в душе хочеться исполнить детскую мечту, Быть губко бобом"),
    ("Что-нибудь придумаем", "Да я знаю ты же предложишь пойти баристо работать, А я бургеры хочу готовить("),
    ("Ну это тоже прикольно. А может на СВО?","Ты дурак? У тебя плоскостопие"),
    ("Бля я бургеры вроде год не ел", "Дак ты ж мой откусывал в бк в желике"),
    ("Я мясо блал", "Ладно"),
    ("Сука, я ещё не завтракал сегодня, сижу на паре как сыч","Бедолага, а я на работе нифига не делаю. Ваще кайфуха"),
    ("А","Дим, Кто такие гетеро, Это пидоры или норм?"),
    ("Норм","Фух, Я уже расстроится хотел"),
    ("Да ты за ночь и дмс проходил","Дак я дмс в 12 часов ночи  начинал проходить. А закончил в 8 и сразу спать лёг"),
    ("Тут ещё чел, ну как ты, только волосы короче. Он 73 весит, а ты вроде 85 Или 80? Как?","Да я уже хз скок вешу"),
    ("прив","В дис будешь"),
    ("Влад, хочешь в дис?","Гоу"),
    ("Оооо у меня незачёт!","Грустно"),
    ("я на соревнованиях второе место занял!","Маладец, Чемпион"),
    ("Торговаться будем?", "Торг не уместен"),
    ("Привет","Дима я знаю что ты не доел мамину кашу"),
    ("Нет, человек-паук, я не хотел(", "Я растроен, разве ты не хочешь быть сильным и помогать мне бороться со злом?"),
    ("Очки кайф","Когда на аву поставишь?"),
    ("Думаю","Ещё не решил"),
    ("Взвешиваю все за и против","Ставь задалбал"),
    ("Нескоро(", "Печаль"),
    ("А я всю ночь просыпался, чтобы опередить будильник, потому что с громкостью тедефона какие-то мутки, но и поспать по дольше", "Не ну это пиздец какой то мне каждую ночь сны сняться, никогда такого не было, только если в детстве"),
    ("Нуууу сегодня да","Что тебе приходиться делать что бы достичь крупицы моих сил"),
    ("Пипец, мне приходится кокой-то фигнёй заниматься, чтобы хотяб какие-то сны снились","Пипец, мне приходится кокой-то фигнёй заниматься, чтобы хотяб какие-то сны снились"),
    ("Привет", "Че"),
    ("Как дела?", "Норм"),
    ("Что делаешь?","Не поверишь, на заводе"),
    ("Как настроение", "Ты чё так резко решил азадачиться моей жизнью"),
    ("пойдём играть?","Пошлмь"),
    ("Как дела?", "Нормально, а у тебя?"),
    ("Что нового?", "Да так, ничего особенного."),
    ("Ты видел новый фильм?", "Нет еще, но хочу посмотреть."),
    ("Как погода?", "Сегодня тепло и солнечно."),
    ("Что будешь делать на выходных?", "Планирую отдохнуть и поиграть."),
    ("Ты уже поел?", "Нет еще, думал заказать что-то."),
    ("Как настроен?", "Нормально, немного устал."),
    ("Когда последний раз был на отдыхе?", "Уже давно не был на море."),
    ("Какой твой любимый напиток?", "Наверное кофе или чай."),
    ("Ты любишь спорт?", "Да, иногда занимаюсь фитнесом."),
    ("Что думаешь о работе?", "Работа есть работа... но иногда скучно."),
    ("Какой твой любимый сериал?", "Смотрел 'Игра престолов' — крутой!"),
    ("Ты когда-нибудь пробовал готовить?", "Да, но чаще заказываю еду из-за нехватки времени."),
    ("Как ты проводишь свободное время?", "Смотрю сериалы и играю в игры."),
    ("Ты любишь путешествовать?", "Да, мечтаю посетить Японию."),
    ("Какой у тебя любимый фильм?", "Наверное, 'Начало' — очень интересный сюжет."),
    ("Что ты думаешь о музыке?", "Музыка помогает мне расслабиться."),
    ("Какой у тебя любимый жанр книг?", "Я люблю фантастику и фэнтези."),
    ("Ты когда-нибудь играл в настольные игры?", "Да, очень люблю 'Монополию' и 'Мафию'."),
    ("Какой твой любимый вид спорта?", "Футбол, я болею за свою команду."),
    ("Ты часто ходишь в кино?", "Не так часто, но иногда выбираюсь с друзьями."),
    ("Какой твой любимый праздник?", "Новый год — всегда весело и интересно."),
    ("Что ты думаешь о социальных сетях?", "Иногда полезно, но бывает и слишком много информации."),
    ("Ты любишь готовить?", "Да, иногда экспериментирую с новыми рецептами."),
    ("Какой твой любимый десерт?", "Обожаю торт 'Наполеон'."),
    ("Ты когда-нибудь был на концерте?", "Да, это было незабываемо!"),
    ("Что ты думаешь о спорте?", "Спорт — это здорово, помогает поддерживать форму."),
    ("Как ты относишься к животным?", "Я люблю животных, у меня есть собака."),
    ("Ты любишь читать книги?", "Да, особенно перед сном."),
    ("Какой твой любимый напиток летом?", "Летом предпочитаю лимонад или холодный чай."),
    ("Что ты планируешь на завтра?", "Планирую поработать и немного отдохнуть."),
    ("Когда у тебя день рождения?", "Мой день рождения в июле."),
    ("Что тебе нравится делать по утрам?", "Утром люблю пить кофе и читать новости."),
    ("Ты часто общаешься с друзьями?", "Да, стараюсь встречаться как можно чаще."),
    ("Какой твой самый запоминающийся момент в жизни?",
     "Когда я закончил школу — это было очень волнительно!"),
    ("Как ты относишься к спорту на свежем воздухе?",
     "Это отлично! Свежий воздух и физическая активность — идеальное сочетание."),
    ("Ты когда-нибудь пробовал йогу?",
     "Да, это помогает расслабиться и сконцентрироваться."),
    ("Что ты думаешь о современных технологиях?",
     "Они очень интересны и упрощают жизнь."),
    ("Какой твой любимый цвет?", "Мне нравится синий."),
    ("Ты любишь животных?", "Да, у меня есть кот."),
    ("Какой твой любимый сезон?", "Я люблю осень — погода идеальная."),
    ("Ты когда-нибудь пробовал экстремальные виды спорта?", "Нет, но мечтаю попробовать парапланеризм."),
    ("Какой у тебя хобби?", "Я увлекаюсь фотографией."),
    ("Что ты думаешь о современных технологиях?", "Они делают жизнь удобнее, но иногда слишком отвлекают."),
    ("Ты любишь готовить?", "Да, особенно выпечку."),
    ("Какое у тебя любимое блюдо?", "Паста с соусом песто — обожаю!"),
    ("Ты когда-нибудь был за границей?", "Да, я был в Испании и Италии."),
    ("Какой твой любимый сериал?", "Смотрел 'Во все тяжкие' — очень захватывающий."),
    ("Ты в чате?","Давай!"),
    ("Саша, ты сегодня на работе?","Нет, а что?"),
    ("Может, встретимся в чате?","Давай!"),
    ("Сейчас умоюсь, поем и зайду","Давай быстрее!"),
    ("Саша, не хочешь в чат через 10 минут?","Давай!"),
    ("Поиграем вместе?","Пошли!"),
    ("Саша, когда ты вернешься?","Через 3 часа, я тут на встрече, так хочется спать!"),
    ("Кто-то вчера говорил, что поест и ляжет спать","А я что, не спал?"),
    ("Пойдем работать в кафе, может, с кем-то познакомишься","Не обнадеживай меня..."),
    ("Саша, ты мне про Мишу рассказывал, и теперь он мне пишет, мне страшно","Осторожно с парнями!"),
    ("А", "Когда-нибудь мы устроимся вместе в пиццерии или суши?"),
    ("Не знаю","Да блин("),
    ("Что случилось?","Да работа работой, а в душе мечтаю стать космонавтом."),
    ("Что-нибудь придумаем", "Я знаю, ты предложишь пойти в бар, а я хочу готовить пиццу("),
    ("Это тоже интересно. Может, на курсы?","Ты что, у тебя же аллергия на занятия!"),
    ("Блин, я пиццу не ел уже целый год","Так ты же пробовал ее у меня на вечеринке!"),
    ("Я только салаты ел","Ладно"),
    ("Черт, я еще не завтракал, сижу на уроке как зомби","Бедняга, а я на работе ничего не делаю. Просто кайф!"),
    ("А","Саша, кто такие геи? Это нормально или нет?"),
    ("Нормально","Фух, я уже переживать начал"),
    ("Ты ночью ДЗ делал?","Я начал в 12 и закончил в 6, потом сразу уснул."),
    ("Тут еще парень, как ты, только с короткой стрижкой. Он весит 70, а ты вроде 85 или 90? Как так?","Я тоже не знаю, сколько вешу"),
    ("Привет","В чат зайдешь?"),
    ("Саша, как насчет чата?","Давай!"),
    ("О, у меня не сдана контрольная!","Печально."),
    ("Я занял второе место на турнире!","Молодец, чемпион!"),
    ("Будем торговаться?","Торговля неуместна."),
    ("Привет","Саша, я знаю, что ты не доел мамину кашу."),
    ("Нет, я не хотел(", "Я расстроен, разве ты не хочешь быть сильным и помогать мне бороться с трудностями?"),
    ("Очки классные","Когда на аватарку поставишь?"),
    ("Думаю","Еще не решил"),
    ("Взвешиваю все за и против","Ставь, надоело!"),
    ("Нескоро(","Грусть"),
    ("Я всю ночь просыпался, чтобы не проспать будильник, потому что с телефоном что-то не так, но и хочется поспать подольше", "Не, это какой-то ужас, мне каждую ночь снятся сны, такого не было, только в детстве"),
    ("Ну да, сегодня да","Что тебе нужно сделать, чтобы достичь хоть капли моих сил?"),
    ("Ужас, мне приходится заниматься ерундой, чтобы хоть какие-то сны снились","Ужас, мне приходится заниматься ерундой, чтобы хоть какие-то сны снились"),
    ("Привет", "Что?"),
    ("Как дела?", "Нормально."),
    ("Что делаешь?","Не поверишь, на заводе"),
    ("Как настроение", "Ты что, так резко решил узнать о моей жизни?"),
    ("Поиграем?","Пошли!"),

    ("Как дела?", "Нормально, а у тебя?"),
    ("Что нового?", "Да так, ничего особенного."),
    ("Ты видел новый фильм?", "Нет еще, но хочу посмотреть."),
    ("Как погода?", "Сегодня тепло и солнечно."),
    ("Что будешь делать на выходных?", "Планирую отдохнуть и поиграть."),
    ("Ты уже поел?", "Нет еще, думал заказать что-то."),
    ("Как настроен?", "Нормально, немного устал."),
    ("Когда последний раз был на отдыхе?", "Уже давно не был на море."),
    ("Какой твой любимый напиток?", "Наверное кофе или чай."),
    ("Ты любишь спорт?", "Да, иногда занимаюсь фитнесом."),

    ("Что думаешь о работе?", "Работа есть работа... но иногда скучно."),
    ("Какой твой любимый сериал?", "Смотрел 'Игра престолов' — крутой!"),
    ("Ты когда-нибудь пробовал готовить?", "Да, но чаще заказываю еду из-за нехватки времени."),
    ("Как ты проводишь свободное время?", "Смотрю сериалы и играю в игры."),
    ("Ты любишь путешествовать?", "Да, мечтаю посетить Японию."),
    ("Какой у тебя любимый фильм?", "Наверное, 'Начало' — очень интересный сюжет."),
    ("Что ты думаешь о музыке?", "Музыка помогает мне расслабиться."),
    ("Какой у тебя любимый жанр книг?", "Я люблю фантастику и фэнтези."),
    ("Ты когда-нибудь играл в настольные игры?", "Да, очень люблю 'Монополию' и 'Мафию'."),
    ("Какой твой любимый вид спорта?", "Футбол, я болею за свою команду."),
    ("Ты часто ходишь в кино?", "Не так часто, но иногда выбираюсь с друзьями."),
    ("Какой твой любимый праздник?", "Новый год — всегда весело и интересно."),
    ("Что ты думаешь о социальных сетях?", "Иногда полезно, но бывает и слишком много информации."),

    ("Ты любишь готовить?", "Да, иногда экспериментирую с новыми рецептами."),
    ("Какой твой любимый десерт?", "Обожаю торт 'Наполеон'."),
    ("Ты когда-нибудь был на концерте?", "Да, это было незабываемо!"),
    ("Что ты думаешь о спорте?", "Спорт — это здорово, помогает поддерживать форму."),
    ("Как ты относишься к животным?", "Я люблю животных, у меня есть собака."),
    ("Ты любишь читать книги?", "Да, особенно перед сном."),
    ("Какой твой любимый напиток летом?", "Летом предпочитаю лимонад или холодный чай."),

    ("Что ты планируешь на завтра?", "Планирую поработать и немного отдохнуть."),
    ("Когда у тебя день рождения?", "Мой день рождения в июле."),
    ("Что тебе нравится делать по утрам?", "Утром люблю пить кофе и читать новости."),
    ("Ты часто общаешься с друзьями?", "Да, стараюсь встречаться как можно чаще."),
    ("Какой твой самый запоминающийся момент в жизни?",
     "Когда я закончил школу — это было очень волнительно!"),

    ("Как ты относишься к спорту на свежем воздухе?",
     "Это отлично! Свежий воздух и физическая активность — идеальное сочетание."),
    ("Ты когда-нибудь пробовал йогу?",
     "Да, это помогает расслабиться и сконцентрироваться."),
    ("Что ты думаешь о современных технологиях?",
     "Они очень интересны и упрощают жизнь."),
    ("Какой твой любимый цвет?", "Мне нравится синий."),
    ("Ты любишь животных?", "Да, у меня есть кот."),
    ("Какой твой любимый сезон?", "Я люблю осень — погода идеальная."),
    ("Ты когда-нибудь пробовал экстремальные виды спорта?", "Нет, но мечтаю попробовать парапланеризм."),
    ("Какой у тебя хобби?", "Я увлекаюсь фотографией."),
    ("Что ты думаешь о современных технологиях?", "Они делают жизнь удобнее, но иногда слишком отвлекают."),
    ("Ты любишь готовить?", "Да, особенно выпечку."),
    ("Какое у тебя любимое блюдо?", "Паста с соусом песто — обожаю!"),
    ("Ты когда-нибудь был за границей?", "Да, я был в Испании и Италии."),
    ("Какой твой любимый сериал?", "Смотрел 'Во все тяжкие' — очень захватывающий."),
    ("Ты в чате?","Давай!"),
    ("Саша, ты сегодня на работе?","Нет, а что?"),
    ("Может, встретимся в чате?","Давай!"),
    ("Сейчас умоюсь, поем и зайду","Давай быстрее!"),
    ("Саша, не хочешь в чат через 10 минут?","Давай!"),
    ("Поиграем вместе?","Пошли!"),
    ("Саша, когда ты вернешься?","Через 3 часа, я тут на встрече, так хочется спать!"),
    ("Кто-то вчера говорил, что поест и ляжет спать","А я что, не спал?"),
    ("Пойдем работать в кафе, может, с кем-то познакомишься","Не обнадеживай меня..."),
    ("Саша, ты мне про Мишу рассказывал, и теперь он мне пишет, мне страшно","Осторожно с парнями!"),
    ("А", "Когда-нибудь мы устроимся вместе в пиццерии или суши?"),
    ("Не знаю","Да блин("),
    ("Что случилось?","Да работа работой, а в душе мечтаю стать космонавтом."),
    ("Что-нибудь придумаем", "Я знаю, ты предложишь пойти в бар, а я хочу готовить пиццу("),
    ("Это тоже интересно. Может, на курсы?","Ты что, у тебя же аллергия на занятия!"),
    ("Блин, я пиццу не ел уже целый год","Так ты же пробовал ее у меня на вечеринке!"),
    ("Я только салаты ел","Ладно"),
    ("Черт, я еще не завтракал, сижу на уроке как зомби","Бедняга, а я на работе ничего не делаю. Просто кайф!"),
    ("А","Саша, кто такие геи? Это нормально или нет?"),
    ("Нормально","Фух, я уже переживать начал"),
    ("Ты ночью ДЗ делал?","Я начал в 12 и закончил в 6, потом сразу уснул."),
    ("Тут еще парень, как ты, только с короткой стрижкой. Он весит 70, а ты вроде 85 или 90? Как так?","Я тоже не знаю, сколько вешу"),
    ("Привет","В чат зайдешь?"),
    ("Саша, как насчет чата?","Давай!"),
    ("О, у меня не сдана контрольная!","Печально."),
    ("Я занял второе место на турнире!","Молодец, чемпион!"),
    ("Будем торговаться?","Торговля неуместна."),
    ("Привет","Саша, я знаю, что ты не доел мамину кашу."),
    ("Нет, я не хотел(", "Я расстроен, разве ты не хочешь быть сильным и помогать мне бороться с трудностями?"),
    ("Очки классные","Когда на аватарку поставишь?"),
    ("Думаю","Еще не решил"),
    ("Взвешиваю все за и против","Ставь, надоело!"),
    ("Нескоро(","Грусть"),
    ("Я всю ночь просыпался, чтобы не проспать будильник, потому что с телефоном что-то не так, но и хочется поспать подольше", "Не, это какой-то ужас, мне каждую ночь снятся сны, такого не было, только в детстве"),
    ("Ну да, сегодня да","Что тебе нужно сделать, чтобы достичь хоть капли моих сил?"),
    ("Ужас, мне приходится заниматься ерундой, чтобы хоть какие-то сны снились","Ужас, мне приходится заниматься ерундой, чтобы хоть какие-то сны снились"),
    ("Привет", "Что?"),
    ("Как дела?", "Нормально."),
    ("Что делаешь?","Не поверишь, на заводе"),
    ("Как настроение", "Ты что, так резко решил узнать о моей жизни?"),
    ("Поиграем?","Пошли!"),

    ("Как дела?", "Нормально, а у тебя?"),
    ("Что нового?", "Да так, ничего особенного."),
    ("Ты видел новый фильм?", "Нет еще, но хочу посмотреть."),
    ("Как погода?", "Сегодня тепло и солнечно."),
    ("Что будешь делать на выходных?", "Планирую отдохнуть и поиграть."),
    ("Ты уже поел?", "Нет еще, думал заказать что-то."),
    ("Как настроен?", "Нормально, немного устал."),
    ("Когда последний раз был на отдыхе?", "Уже давно не был на море."),
    ("Какой твой любимый напиток?", "Наверное кофе или чай."),
    ("Ты любишь спорт?", "Да, иногда занимаюсь фитнесом."),

    ("Что думаешь о работе?", "Работа есть работа... но иногда скучно."),
    ("Какой твой любимый сериал?", "Смотрел 'Игра престолов' — крутой!"),
    ("Ты когда-нибудь пробовал готовить?", "Да, но чаще заказываю еду из-за нехватки времени."),
    ("Как ты проводишь свободное время?", "Смотрю сериалы и играю в игры."),
    ("Ты любишь путешествовать?", "Да, мечтаю посетить Японию."),
    ("Какой у тебя любимый фильм?", "Наверное, 'Начало' — очень интересный сюжет."),
    ("Что ты думаешь о музыке?", "Музыка помогает мне расслабиться."),
    ("Какой у тебя любимый жанр книг?", "Я люблю фантастику и фэнтези."),
    ("Ты когда-нибудь играл в настольные игры?", "Да, очень люблю 'Монополию' и 'Мафию'."),
    ("Какой твой любимый вид спорта?", "Футбол, я болею за свою команду."),
    ("Ты часто ходишь в кино?", "Не так часто, но иногда выбираюсь с друзьями."),
    ("Какой твой любимый праздник?", "Новый год — всегда весело и интересно."),
    ("Что ты думаешь о социальных сетях?", "Иногда полезно, но бывает и слишком много информации."),

    ("Ты любишь готовить?", "Да, иногда экспериментирую с новыми рецептами."),
    ("Какой твой любимый десерт?", "Обожаю торт 'Наполеон'."),
    ("Ты когда-нибудь был на концерте?", "Да, это было незабываемо!"),
    ("Что ты думаешь о спорте?", "Спорт — это здорово, помогает поддерживать форму."),
    ("Как ты относишься к животным?", "Я люблю животных, у меня есть собака."),
    ("Ты любишь читать книги?", "Да, особенно перед сном."),
    ("Какой твой любимый напиток летом?", "Летом предпочитаю лимонад или холодный чай."),

    ("Что ты планируешь на завтра?", "Планирую поработать и немного отдохнуть."),
    ("Когда у тебя день рождения?", "Мой день рождения в июле."),
    ("Что тебе нравится делать по утрам?", "Утром люблю пить кофе и читать новости."),
    ("Ты часто общаешься с друзьями?", "Да, стараюсь встречаться как можно чаще."),
    ("Какой твой самый запоминающийся момент в жизни?",
     "Когда я закончил школу — это было очень волнительно!"),

    ("Как ты относишься к спорту на свежем воздухе?",
     "Это отлично! Свежий воздух и физическая активность — идеальное сочетание."),
    ("Ты когда-нибудь пробовал йогу?",
     "Да, это помогает расслабиться и сконцентрироваться."),
    ("Что ты думаешь о современных технологиях?",
     "Они очень интересны и упрощают жизнь."),
    ("Какой твой любимый цвет?", "Мне нравится синий."),
    ("Ты любишь животных?", "Да, у меня есть кот."),
    ("Какой твой любимый сезон?", "Я люблю осень — погода идеальная."),
    ("Ты когда-нибудь пробовал экстремальные виды спорта?", "Нет, но мечтаю попробовать парапланеризм."),
    ("Какой у тебя хобби?", "Я увлекаюсь фотографией."),
    ("Что ты думаешь о современных технологиях?", "Они делают жизнь удобнее, но иногда слишком отвлекают."),
    ("Ты любишь готовить?", "Да, особенно выпечку."),
    ("Какое у тебя любимое блюдо?", "Паста с соусом песто — обожаю!"),
    ("Ты когда-нибудь был за границей?", "Да, я был в Испании и Италии."),
    ("Какой твой любимый сериал?", "Смотрел 'Во все тяжкие' — очень захватывающий."),
    ("Го в дис через пол часика?" ,"Les go"),
    ("Ты спишь?", "Ну спал"),
    ("Как насчет дискуссии?", "Давай"),
    ("Влад, работаешь сегодня?", "Нет, а что?"),
    ("Думал, может, соберемся?", "Давай"),
    ("Сейчас помоюсь, разогрею еду и буду готов", "Давай побыстрее"),
    ("Влад, не хочешь встретиться через пять минут?", "Давай"),
    ("Пойдем играть?", "Да, давай"),
    ("Влад, когда вернешься домой?", "Еще три часа работы. Я сейчас нанесу убыток в миллион рублей, как же хочется спать"),
    ("Кто-то вчера говорил, что покушает и ляжет спать", "Так а я что делаю?"),
    ("Пойдем работать в 'Жилище', может, с той девушкой и поговоришь", "Не стоит дарить мне надежды..."),
    ("Влад, ты говорил про Девинчика, он мне написал, мне страшно", "Бойся женщин"),
    ("А можно когда-нибудь вместе устроиться работать в 'Бургер Кинг' или 'Макдак'?", "Не знаю"),
    ("Не уверен", "Да блин..."),
    ("А что?", "Да, завод есть завод, но в душе хочется осуществить детскую мечту — стать Губкой Бобом"),
    ("Найдем что-то", "Знаю, ты предложишь пойти работать баристом, а я хочу готовить бургеры"),
    ("Это тоже интересно. А может, в СВО?", "Ты в своем уме? У тебя плоскостопие"),
    ("Блин, я не ел бургеры почти год", "Но ты же пробовал мои в 'Бургер Кинг' в 'Жилище'"),
    ("Я про мясо", "Ладно"),
    ("Черт, я еще не завтракам, сижу на паре как сыч", "Бедняга, а я на работе вообще ничего не делаю, кайф"),
    ("А", "Дим, кто такие гетеросексуалы, это норм или нет?"),
    ("Норм", "Фух, уже хотел расстраиваться"),
    ("Ты за ночь и ДМС проходил", "Да, я проходил ДМС с 12 ночи до 8, а потом сразу лег спать"),
    ("Тут еще парень, похож на тебя, только волосы короче. Он 73 кг, а ты, кажется, 85 или 80? Как так?", "Не знаю, сколько вешу"),
    ("Привет", "Ты в дискуссионную группу пойдешь?"),
    ("Влад, хочешь в дискуссию?", "Давай"),
    ("О, у меня незасчитанные оценки!", "Грустно"),
    ("Я занял второе место на соревнованиях!", "Молодец, чемпион!"),
    ("Будем торговаться?", "Торг не уместен"),
    ("Привет", "Дима, я знаю, что ты не доел кашу от мамы"),
    ("Нет, Человек-паук, я этого не хотел(", "Я расстроен, разве ты не хочешь быть сильным и помочь мне бороться со злом?"),
    ("Очки классные", "Когда поставишь на аватар?"),
    ("Думаю об этом", "Еще не решил"),
    ("Взвешиваю все за и против", "Ставь, надоели уже"),
    ("Не скоро(", "Печаль"),
    ("Я всю ночь просыпался, чтобы предвосхитить будильник, потому что с громкостью телефона что-то непорядок, а поспать бы подольше", "Да, это вообще абсурд, мне каждую ночь снятся сны, никогда такого не было, только в детстве"),
    ("Сегодня да", "Что тебе нужно делать, чтобы достичь хотя бы капельки моих сил?"),
    ("Пипец, мне приходится заниматься какой-то чепухой, чтобы хоть какие-то сны снились", "Пипец, мне тоже приходится заниматься какой-то фигней, чтобы хоть какие-то сны снились"),
    ("Привет", "Что?"),
    ("Как дела?", "Нормально"),
    ("Что делаешь?", "Не поверишь, работаю на заводе"),
    ("Как настроение?", "Ты что, так резко интересуешься моей жизнью?"),
    ("Пойдем играть?", "Да, давай"),
    ("Как дела?", "Нормально, а у тебя?"),
    ("Что нового?", "Да так, ничего особенного."),
    ("Ты смотрел новый фильм?", "Нет, а хочу посмотреть."),
    ("Как погода?", "Сегодня тепло и солнечно."),
    ("Что будешь делать на выходных?", "Планирую отдохнуть и поиграть."),
    ("Ты уже поел?", "Нет, думал заказать что-то."),
    ("Как настроен?", "Нормально, немного устал."),
    ("Когда был последний раз на отдыхе?", "Уже давно не был на море."),
    ("Какой твой любимый напиток?", "Наверное, кофе или чай."),
    ("Ты любишь спорт?", "Да, иногда занимаюсь фитнесом."),
    ("Что думаешь о работе?", "Работа есть работа... но иногда скучно."),
    ("Какой твой любимый сериал?", "Смотрел 'Игру престолов' — крутой!"),
    ("Ты когда-нибудь готовил?", "Да, но чаще заказываю еду из-за нехватки времени."),
    ("Как проводишь свободное время?", "Смотрю сериалы и играю в игры."),
    ("Ты любишь путешествовать?", "Да, мечтаю посетить Японию."),
    ("Какой у тебя любимый фильм?", "Наверное, 'Начало' — очень интересный сюжет."),
    ("Что ты думаешь о музыке?", "Музыка помогает мне расслабиться."),
    ("Какой у тебя любимый жанр книг?", "Я люблю фантастику и фэнтези."),
    ("Ты играл в настольные игры?", "Да, очень люблю 'Монополию' и 'Мафию'."),
    ("Какой твой любимый вид спорта?", "Футбол, я болею за свою команду."),
    ("Ты часто ходишь в кино?", "Не так часто, но иногда выбираюсь с друзьями."),
    ("Какой твой любимый праздник?", "Новый год — всегда весело и интересно."),
    ("Что ты думаешь о соцсетях?", "Иногда полезно, но иногда слишком много информации."),
    ("Ты любишь готовить?", "Да, иногда экспериментирую с новыми рецептами."),
    ("Какой твой любимый десерт?", "Обожаю торт 'Наполеон'."),
    ("Ты когда-нибудь был на концерте?", "Да, это было незабываемо!"),
    ("Что ты думаешь о спорте?", "Спорт — это здорово, помогает поддерживать форму."),
    ("В дискорд?", "Давай!"),
    ("Влад, ты сегодня на работе?", "Нет, а что?"),
    ("Думал, может, зайдём в дискорд?", "Так давай!"),
    ("Сейчас помоюсь, разогрею еду и буду готов", "Давай быстрее!"),
    ("Влад, не хочешь зайти в дискорд через 5 минут?", "Давай!"),
    ("Пойдём поиграем?", "Давай!"),
    ("Влад, когда ты будешь дома?", "Через 3 часа, до конца смены. Я сейчас накосячу на миллион рублей, как же хочется спать."),
    ("Кто-то говорил, что поест и ляжет спать", "А я что сделал?"),
    ("Давай работать в желтом на бк, может, с той девушкой познакомишься", "Не надо мне давать надежды..."),
    ("Влад, ты мне про Давидчика говорил, а теперь он мне пишет, мне страшно", "Бойся девушек."),
    ("А", "Можно когда-нибудь устроиться вместе в Бургер Кинг или Макдональдс?"),
    ("Не знаю", "Да уж("),
    ("А что?", "Да, работа работой, а в душе хочется исполнить детскую мечту — стать Губкой Бобом."),
    ("Что-нибудь придумаем", "Да я знаю, ты снова предложишь стать баристой, а я хочу готовить бургеры("),
    ("Это тоже интересно. А может на СВО?", "Ты что, с ума сошел? У тебя плоскостопие!"),
    ("Блин, я вроде год не ел бургеры", "Так ты же мои в БК в желтом откусывал."),
    ("Я ел мясо", "Ладно."),
    ("Чёрт, я ещё не завтракал, сижу на паре как зомби", "Бедняга, а я на работе ничего не делаю. Вообще кайф."),
    ("А", "Дим, кто такие гетеро? Это нормальные люди или нет?"),
    ("Нормальные", "Фух, я уже расстроиться хотел."),
    ("Ты же ночью ДМС проходил?", "Я начал проходить ДМС в 12 ночи и закончил в 8, сразу лег спать."),
    ("Тут ещё парень, как ты, только с короткими волосами. Он весит 73, а ты вроде 85 или 80? Как так?", "Да я уже не знаю, сколько вешу."),
    ("Привет", "Ты в дискорд зайдёшь?"),
    ("Влад, идёшь в дискорд?", "Давай!"),
    ("О, у меня незачёт!", "Грустно."),


    ("В дискорд?", "Погнали"),
    ("Влад, ты сегодня на работе?", "Нет, а что?"),
    ("Думал, может, в дискорд?", "Так погнали"),
    ("Сейчас умоюсь, разогрею еду и буду готов", "Давай быстрее"),
    ("Влад, не хочешь зайти в дискорд через 5 минут?", "Давай"),
    ("Пойдём поиграем?", "Пошли"),
    ("Влад, когда ты вернёшься домой?", "Через три часа, до конца смены. Я сейчас собираюсь устроить материальный ущерб на миллион рублей, как же хочется спать."),
    ("Кто-то вчера говорил, что покушает и ляжет спать", "Так я и сделал."),
    ("Го работать в желтом, может, познакомишься с той девушкой", "Не надо давать мне надежды…"),
    ("Влад, ты мне про Давидчика написал, и теперь он мне пишет, мне страшно", "Бойся женщин."),
    ("А", "Может, когда-нибудь мы устроимся вместе в Бургер Кинг или Макдональдс?"),
    ("Не знаю", "Да блин("),
    ("А что?", "Завод заводом, а в душе хочется исполнить детскую мечту — быть Губкой Бобом."),
    ("Что-нибудь придумаем", "Да я знаю, ты предложишь пойти работать баристом, а я хочу готовить бургеры("),
    ("Это тоже интересно. Может быть на СВО?", "Ты что, дурак? У тебя плоскостопие."),
    ("Блин, я вроде год не ел бургеры", "Так ты же мои пробовал в БК в желтом."),
    ("Я мясо имел в виду", "Ладно."),
    ("Чёрт, я ещё не завтракал сегодня, сижу на паре как сова", "Бедняга, а я на работе ничего не делаю. Вообще кайф."),
    ("А", "Дим, кто такие гетеросексуалы? Это нормальные люди или нет?"),
    ("Нормальные", "Фух, я уже начал переживать."),
    ("Ты за ночь и ДМС прошёл", "Я начал проходить ДМС в 12 ночи и закончил в 8, а потом сразу лег спать."),
    ("Тут есть ещё парень, похожий на тебя, только с короткими волосами. Он весит 73 кг, а ты вроде 85 или 80? Как так?", "Да я уже не знаю, сколько весю."),
    ("Привет", "Ты будешь в дискорде?"),
    ("Влад, хочешь зайти в дискорд?", "Давай."),
    ("Оооо у меня незачёт!", "Грустно."),
    ("Я занял второе место на соревнованиях!", "Молодец! Чемпион!"),
    ("Будем торговаться?", "Торг неуместен."),
    ("Привет", "Дима, я знаю, что ты не доел мамину кашу."),
    ("Нет, человек-паук, я не хотел(", "Я расстроен! Разве ты не хочешь быть сильным и помогать мне бороться со злом?"),
    ("Очки классные", "Когда поставишь на аватарку?"),
    ("Думаю", "Ещё не решил."),
    ("Взвешиваю все за и против", "Ставь задалбал."),
    ("Нескоро(", "Печально."),
    ("Я всю ночь просыпался, чтобы опередить будильник — какие-то проблемы со звуком телефона; но хотелось бы поспать подольше.",
    "Не ну это какой-то кошмар! Мне каждую ночь снятся сны — никогда такого не было, только в детстве."),
    ("Ну да, сегодня да",
    "Что тебе нужно сделать, чтобы достичь хотя бы капли моих сил?"),
    ("Ужас! Мне приходится заниматься какой-то ерундой лишь для того, чтобы хоть какие-то сны снились.",
    "Ужас! Мне приходится заниматься какой-то ерундой лишь для того, чтобы хоть какие-то сны снились."),
    ("Привет", "Что нового?"),
    ("Как дела?", "Нормально."),
    ("Что делаешь?",
    "Не поверишь — на заводе."),
    ("Как настроение?",
    "Почему ты так резко решил интересоваться моей жизнью?"),
    ("Пойдём поиграем?",
    "Пошли."),
    ("Как дела?",
    "Нормально, а у тебя как?"),
    ("Что нового?",
    "Да так — ничего особенного."),
    ("Ты видел новый фильм?",
    "Нет ещё, но хочу посмотреть."),
    ("Как погода?",
    "Сегодня тепло и солнечно."),
    ("Что будешь делать на выходных?",
    "Планирую отдохнуть и поиграть."),
    ("Ты уже поел?",
    "Нет ещё; думал заказать что-то."),
    ("Как настроен?",
    "Нормально; немного устал."),
    ("Когда последний раз был на отдыхе?",
    "Уже давно не был на море."),
    ("Какой твой любимый напиток?",
    "Наверное кофе или чай."),
    ("Ты любишь спорт?",
    "Да; иногда занимаюсь фитнесом."),
    ("Что думаешь о работе?",
    "Работа есть работа… но иногда скучно."),
    ("Какой твой любимый сериал?",
    "'Игра престолов' — крутой!"),
    ("Ты когда-нибудь пробовал готовить?",
    "Да; но чаще заказываю еду из-за нехватки времени."),
    ("Как ты проводишь свободное время?",
    "Смотрю сериалы и играю в игры."),
    ("Ты любишь путешествовать?",
    "Да; мечтаю посетить Японию."),
    ("Какой у тебя любимый фильм?",
    "'Начало' — очень интересный сюжет."),
    ("Что ты думаешь о музыке?",
    "Музыка помогает мне расслабиться."),
    ("Какой у тебя любимый жанр книг?",
    "Я люблю фантастику и фэнтези."),
    ("Ты когда-нибудь играл в настольные игры?",
    "Да; очень люблю 'Монополию' и 'Мафию'."),
    ("Какой твой любимый вид спорта?",
    "Футбол; я болею за свою команду."),
    ("Ты часто ходишь в кино?",
    "Не так часто; но иногда выбираюсь с друзьями."),
    ("Какой твой любимый праздник?",
    "Новый год — всегда весело и интересно."),
    ("Что ты думаешь о социальных сетях?",
    "Иногда полезно; но бывает слишком много информации."),
    ("Ты любишь готовить?",
    "Да; иногда экспериментирую с новыми рецептами."),
    ("Какой твой любимый десерт?",
    "'Наполеон' — обожаю его!"),
    ("Ты когда-нибудь был на концерте?",
    "Да; это было незабываемо!"),
    ("Что ты думаешь о спорте?",
    "Спорт — это здорово; помогает поддерживать форму."),
    ("В Дискорд?", "Погнали!"),
    ("Влад, ты сегодня работаешь?", "Нет, а что случилось?"),
    ("Думал, может, зайдём в Дискорд?", "Так давай!"),
    ("Сейчас умоюсь, разогрею еду и буду готов", "Давай поторопись!"),
    ("Влад, не хочешь зайти в Дискорд через 5 минут?", "Давай!"),
    ("Пойдём поиграем?", "Пошли!"),
    ("Влад, когда ты вернёшься домой?", "Через три часа, до конца смены. Я собираюсь устроить материальный ущерб на миллион рублей, так хочется спать."),
    ("Кто-то говорил, что покушает и ляжет спать", "Так я и сделал."),
    ("Го работать в жёлтом, может, познакомишься с девушкой", "Не надо давать мне надежд…"),
    ("Влад, ты мне про Давидчика рассказал, и теперь он мне пишет, мне страшно", "Бойся женщин."),
    ("А", "Может, когда-нибудь устроимся вместе в Бургер Кинг или Макдональдс?"),
    ("Не знаю", "Да блин("),
    ("А что?", "Завод — это одно, а в душе хочется исполнить детскую мечту — быть Губкой Бобом."),
    ("Что-нибудь придумаем", "Да я знаю, ты предложишь работать баристом, а я хочу готовить бургеры("),
    ("Это тоже интересно. Может, на СВО?", "Ты что, дурак? У тебя плоскостопие."),
    ("Блин, я вроде год не ел бургеров", "Так ты же мои пробовал в БК в жёлтом."),
    ("Я мясо имел в виду", "Ладно."),
    ("Чёрт, я ещё не завтракал сегодня, сижу на паре как сова", "Бедняга, а я на работе ничего не делаю. Вообще кайф."),
    ("А", "Дим, кто такие гетеросексуалы? Это нормальные люди или нет?"),
    ("Нормальные", "Фух, я уже начал переживать."),
    ("Ты прошёл ночь и ДМС", "Я начал проходить ДМС в 12 ночи и закончил в 8, а потом сразу лёг спать."),
    ("Тут есть парень, похожий на тебя, только с короткими волосами. Он весит 73 кг, а ты вроде 85 или 80? Как так?", "Да я уже не знаю, сколько весю."),
    ("Привет", "Ты будешь в Дискорде?"),
    ("Влад, хочешь зайти в Дискорд?", "Давай."),
    ("Оооо, у меня незачёт!", "Грустно."),
    ("Я занял второе место на соревнованиях!", "Молодец! Чемпион!"),
    ("Будем торговаться?", "Торг неуместен."),
    ("Привет", "Дима, я знаю, что ты не доел мамину кашу."),
    ("Нет, человек-паук, я не хотел(", "Я расстроен! Разве ты не хочешь быть сильным и помогать мне бороться со злом?"),
    ("Очки классные", "Когда поставишь на аватарку?"),
    ("Думаю", "Ещё не решил."),
    ("Взвешиваю все за и против", "Ставь, задолбал."),
    ("Нескоро(", "Печально."),
    ("Я всю ночь просыпался, чтобы опередить будильник — какие-то проблемы со звуком телефона; но хотелось бы поспать подольше.", "Не ну это какой-то кошмар! Мне каждую ночь снятся сны — никогда такого не было, только в детстве."),
    ("Ну да, сегодня да", "Что нужно сделать, чтобы достичь хотя бы капли моих сил?"),
    ("Ужас! Мне приходится заниматься какой-то ерундой, лишь бы хоть какие-то сны снились.", "Ужас! Мне приходится заниматься какой-то ерундой, лишь бы хоть какие-то сны снились."),
    ("Привет", "Что нового?"),
    ("Как дела?", "Нормально."),
    ("Чем занимаешься?", "Не поверишь — на заводе."),
    ("Как настроение?", "Почему ты так резко решил интересоваться моей жизнью?"),
    ("Пойдём поиграем?", "Пошли."),
    ("Как дела?", "Нормально, а у тебя как?"),
    ("Что нового?", "Да так — ничего особенного."),
    ("Ты видел новый фильм?", "Нет ещё, но хочу посмотреть."),
    ("Как погода?", "Сегодня тепло и солнечно."),
    ("Что будешь делать на выходных?", "Планирую отдохнуть и поиграть."),
    ("Ты уже поел?", "Нет ещё; думал заказать что-то."),
    ("Как настроен?", "Нормально; немного устал."),
    ("Когда последний раз был на отдыхе?", "Уже давно не был на море."),
    ("Какой твой любимый напиток?", "Наверное, кофе или чай."),
    ("Ты любишь спорт?", "Да; иногда занимаюсь фитнесом."),
    ("Что думаешь о работе?", "Работа есть работа… но иногда скучно."),
    ("Какой твой любимый сериал?", "'Игра престолов' — крутой!"),
    ("Ты когда-нибудь пробовал готовить?", "Да; но чаще заказываю еду из-за нехватки времени."),
    ("Как ты проводишь свободное время?", "Смотрю сериалы и играю в игры."),
    ("Ты любишь путешествовать?", "Да; мечтаю посетить Японию."),
    ("Какой у тебя любимый фильм?", "'Начало' — очень интересный сюжет."),
    ("Что ты думаешь о музыке?", "Музыка помогает мне расслабиться."),
    ("Какой у тебя любимый жанр книг?", "Я люблю фантастику и фэнтези."),
    ("Ты когда-нибудь играл в настольные игры?", "Да; очень люблю 'Монополию' и 'Мафию'."),
    ("Какой твой любимый вид спорта?", "Футбол; я болею за свою команду."),
    ("Ты часто ходишь в кино?", "Не так часто; но иногда выбираюсь с друзьями."),
    ("Какой твой любимый праздник?", "Новый год — всегда весело и интересно."),
    ("Что ты думаешь о социальных сетях?", "Иногда полезно; но бывает слишком много информации."),
    ("Ты любишь готовить?", "Да; иногда экспериментирую с новыми рецептами."),
    ("Какой твой любимый десерт?", "'Наполеон' — обожаю его!"),
    ("Ты когда-нибудь был на концерте?", "Да; это было незабываемо!"),
    ("Что ты думаешь о спорте?", "Спорт — это здорово; помогает поддерживать форму."),
    ("Зайдем в Дискорд?", "Отлично, давай!"),
    ("Влад, ты сегодня на работе?", "Нет, а что случилось?"),
    ("Думал, может, поиграем в Дискорде?", "Давай сделаем это!"),
    ("Сейчас умоюсь и разогрею еду, и буду готов", "Поторопись!"),
    ("Влад, не хочешь зайти в Дискорд через пять минут?", "Да, давай!"),
    ("Поиграем вместе?", "С удовольствием!"),
    ("Когда ты вернешься домой, Влад?", "Через три часа, до конца смены. Так хочется спать!"),
    ("Кто-то говорил, что покушает и ляжет спать", "Именно так я и поступил."),
    ("Давай работать в жёлтом, вдруг познакомишься с девушкой", "Не стоит мне давать надежды…"),
    ("Влад, ты рассказал мне про Давидчика, и теперь он мне пишет, мне страшно", "Осторожней с женщинами."),
    ("А", "Может, когда-нибудь устроимся вместе в Бургер Кинг или Макдональдс?"),
    ("Не уверен", "Да блин("),
    ("А что?", "Работа на заводе — это одно, но в душе я мечтаю быть Губкой Бобом."),
    ("Что-нибудь придумаем", "Знаю, ты предложишь стать баристом, а я хочу готовить бургеры("),
    ("Это тоже интересно. Может, на СВО?", "Ты что, дурак? У тебя плоскостопие."),
    ("Блин, я вроде как год не ел бургеров", "Но ты же пробовал мои в БК в жёлтом."),
    ("Я про мясо", "Ладно."),
    ("Чёрт, я ещё не завтракал сегодня, сижу на паре как сова", "Бедняга, а я на работе ничего не делаю. Просто кайф."),
    ("А", "Дим, кто такие гетеросексуалы? Это нормальные люди или нет?"),
    ("Нормальные", "Фух, я уже начал волноваться."),
    ("Ты прошёл ночь и ДМС", "Я начал проходить ДМС в полночь и закончил в 8, а потом сразу лёг спать."),
    ("Тут есть парень, который на тебя похож, только с короткими волосами. Он весит 73 кг, а ты вроде 85 или 80? Как так?", "Да я уже не знаю, сколько вешу."),
    ("Привет", "Ты будешь в Дискорде?"),
    ("Влад, хочешь зайти в Дискорд?", "Давай, конечно."),
    ("Оооо, у меня незачёт!", "Грустно."),
    ("Я занял второе место на соревнованиях!", "Молодец! Настоящий чемпион!"),
    ("Будем торговаться?", "Торг неуместен."),
    ("Привет", "Дима, я знаю, что ты не доел мамину кашу."),
    ("Нет, человек-паук, я не хотел(", "Я расстроен! Разве ты не хочешь быть сильным и помогать мне бороться со злом?"),
    ("Очки классные", "Когда поставишь на аватарку?"),
    ("Думаю", "Ещё не решил."),
    ("Взвешиваю все за и против", "Ставь, задолбал."),
    ("Нескоро(", "Печально."),
    ("Я всю ночь просыпался, чтобы не проспать будильник — какие-то проблемы со звуком телефона; но хотелось бы поспать подольше.", "Не ну это какой-то ужас! Мне каждую ночь снятся сны — никогда такого не было, только в детстве."),
    ("Да, сегодня да", "Что нужно сделать, чтобы хотя бы немного восстановить силы?"),
    ("Ужас! Мне приходится заниматься какой-то ерундой, лишь бы хоть какие-то сны снились.", "Ужас! Мне приходится заниматься какой-то ерундой, лишь бы хоть какие-то сны снились."),
    ("Привет", "Что нового у тебя?"),
    ("Как дела?", "Нормально."),
    ("Чем занимаешься?", "Не поверишь — на заводе."),
    ("Как настроение?", "Почему ты так резко решил интересоваться моей жизнью?"),
    ("Поиграем?", "Пошли."),
    ("Как дела?", "Нормально, а у тебя как?"),
    ("Что нового?", "Да так — ничего особенного."),
    ("Ты видел новый фильм?", "Нет ещё, но хочу посмотреть."),
    ("Как погода?", "Сегодня тепло и солнечно."),
    ("Что планируешь на выходных?", "Планирую отдохнуть и поиграть."),
    ("Ты уже поел?", "Нет ещё; думал заказать что-то."),
    ("Как настроение?", "Нормально; немного устал."),
    ("Когда последний раз был на отдыхе?", "Уже давно не был на море."),
    ("Какой твой любимый напиток?", "Наверное, кофе или чай."),
    ("Ты любишь спорт?", "Да; иногда занимаюсь фитнесом."),
    ("Что думаешь о работе?", "Работа есть работа… но иногда скучно."),
    ("Какой твой любимый сериал?", "'Игра престолов' — очень крутой!"),
    ("Ты когда-нибудь готовил?", "Да; но чаще заказываю еду из-за нехватки времени."),
    ("Как проводишь свободное время?", "Смотрю сериалы и играю в игры."),
    ("Ты любишь путешествовать?", "Да; мечтаю посетить Японию."),
    ("Какой у тебя любимый фильм?", "'Начало' — очень интересный сюжет."),
    ("Что думаешь о музыке?", "Музыка помогает мне расслабиться."),
    ("Какой у тебя любимый жанр книг?", "Я люблю фантастику и фэнтези."),
    ("Ты когда-нибудь играл в настольные игры?", "Да; очень люблю 'Монополию' и 'Мафию'."),
    ("Какой твой любимый вид спорта?", "Футбол; я болею за свою команду."),
    ("Ты часто ходишь в кино?", "Не так часто; но иногда выбираюсь с друзьями."),
    ("Какой твой любимый праздник?", "Новый год — всегда весело и интересно."),
    ("Что ты думаешь о социальных сетях?", "Иногда полезно; но бывает слишком много информации."),
    ("Ты любишь готовить?", "Да; иногда экспериментирую с новыми рецептами."),
    ("Какой твой любимый десерт?", "'Наполеон' — обожаю его!"),
    ("Ты когда-нибудь был на концерте?", "Да; это было незабываемо!"),
    ("Что ты думаешь о спорте?", "Спорт — это здорово; помогает поддерживать форму."),
    ("В дискорд?", "Пойдём"),
    ("Влад, ты сегодня на работе?", "Нет, а что?"),
    ("Думал, может, в дискорд?", "Так давай"),
    ("Сейчас помоюсь, разогрею еду и буду готов", "Давай быстрее"),
    ("Влад, не хочешь зайти в дискорд через 5 минут?", "Давай"),
    ("Пойдём поиграем?", "Поехали"),
    ("Влад, когда ты вернёшься домой?", "Через три часа. Я сейчас нанесу ущерб на миллион рублей, как же хочется спать"),
    ("Кто-то вчера говорил, что покушает и ляжет спать", "Так а я что сделал?"),
    ("Го работать в желтую точку, может с той девушкой познакомишься", "Не надо давать мне надежды…"),
    ("Влад, ты мне про Давидчика написал, и теперь он мне пишет, мне страшно", "Бойся женщин"),
    ("А", "Может когда-нибудь устроимся вместе в Бургер Кинг или Макдональдс?"),
    ("Не знаю", "Да блин("),
    ("А что?", "Завод заводом, а в душе хочу исполнить детскую мечту — быть Губкой Бобом"),
    ("Что-нибудь придумаем", "Да я знаю, ты же предложишь пойти работать баристой, а я хочу готовить бургеры("),
    ("Это тоже прикольно. А может на СВО?", "Ты дурак? У тебя плоскостопие"),
    ("Блин, я бургеры вроде год не ел", "Так ты же мои откусывал в БК в желтой точке"),
    ("Я мясо ел", "Ладно"),
    ("Чёрт, я ещё не завтракал сегодня, сижу на паре как сыч", "Бедняга, а я на работе ничего не делаю. Вообще кайф"),
    ("А", "Дим, кто такие гетеросексуалы? Это пидоры или нормальные люди?"),
    ("Нормальные", "Фух, я уже расстраиваться начал"),
    ("Ты за ночь ДМС проходил", "Так я ДМС в 12 ночи начинал проходить. Закончился в 8 и сразу спать лёг"),
    ("Тут ещё парень, как ты, только волосы короче. Он весит 73, а ты вроде 85 или 80? Как так?", "Да я уже не знаю, сколько вешу"),
    ("Привет", "В дискорд будешь?"),
    ("Влад, хочешь в дискорд?", "Давай!"),
    ("Оооо, у меня незачёт!", "Грустно"),
    ("Я на соревнованиях занял второе место!", "Молодец, чемпион!"),
    ("Будем торговаться?", "Торг неуместен"),
    ("Привет", "Дима, я знаю, что ты не доел мамину кашу"),
    ("Нет, человек-паук, я не хотел(", "Я расстроен. Разве ты не хочешь быть сильным и помогать мне бороться со злом?"),
    ("Очки классные", "Когда поставишь на аватарку?"),
    ("Думаю об этом", "Ещё не решил"),
    ("Взвешиваю все за и против", "Ставь задалбал"),
    ("Нескоро(", "Печально"),
    ("А я всю ночь просыпался, чтобы опередить будильник. С телефоном какие-то мутки с громкостью. Хотел поспать подольше",
     "Не ну это какой-то ужас. Мне каждую ночь снятся сны. Никогда такого не было — только в детстве."),
    ("Ну сегодня да", "Что тебе нужно делать, чтобы достичь хотя бы капли моих сил?"),
    ("Ужасно! Мне приходится заниматься какой-то фигнёй, чтобы хоть какие-то сны снились",
     "Ужасно! Мне приходится заниматься какой-то фигнёй, чтобы хоть какие-то сны снились."),
    ("Привет", "Что?"),
    ("Как дела?", "Нормально."),
    ("Что делаешь?", "Не поверишь — на заводе."),
    ("Как настроение?", "Почему ты так резко решил поинтересоваться моей жизнью?"),
    ("Пойдём поиграем?", "Поехали!"),
    ("Как дела?", "Нормально. А у тебя как?"),
    ("Что нового?", "Да так — ничего особенного."),
    ("Ты видел новый фильм?", "Нет ещё, но хочу посмотреть."),
    ("Как погода?", "Сегодня тепло и солнечно."),
    ("Что планируешь делать на выходных?", "Планирую отдохнуть и поиграть."),
    ("Ты уже поел?", "Нет ещё. Думал заказать что-то."),
    ("Как настроен?", "Нормально. Немного устал."),
    ("Когда последний раз был на отдыхе?", "Уже давно не был на море."),
    ("Какой твой любимый напиток?", "Наверное кофе или чай."),
    ("Ты любишь спорт?", "Да, иногда занимаюсь фитнесом."),
    ("Что думаешь о работе?", "Работа есть работа… но иногда скучно."),
    ("Какой твой любимый сериал?", "'Игра престолов' — крутой!"),
    ("Ты когда-нибудь пробовал готовить?",
     "Да, но чаще заказываю еду из-за нехватки времени."),
    ("Как проводишь свободное время?",
     "Смотрю сериалы и играю в игры."),
    ("Ты любишь путешествовать?",
     "Да, мечтаю посетить Японию."),
    ("Какой у тебя любимый фильм?",
     "'Начало' — очень интересный сюжет."),
    ("Что думаешь о музыке?",
     "Музыка помогает мне расслабиться."),
    ("Какой твой любимый жанр книг?",
     "Я люблю фантастику и фэнтези."),
    ("Ты когда-нибудь играл в настольные игры?",
     "Да, очень люблю 'Монополию' и 'Мафию'."),
    ("Какой твой любимый вид спорта?",
     "Футбол — я болею за свою команду."),
    ("Ты часто ходишь в кино?",
     "Не так часто, но иногда выбираюсь с друзьями."),
  	("Какой твой любимый праздник?",
  		"Новый год — всегда весело и интересно."),
  	("Что думаешь о социальных сетях?",
  		"Иногда полезно, но бывает и слишком много информации."),
  	("Ты любишь готовить?",
  		"Да, иногда экспериментирую с новыми рецептами."),
  	("Какой твой любимый десерт?",
  		"Обожаю торт 'Наполеон'."),
  	("Ты когда-нибудь был на концерте?",
  		"Да — это было незабываемо!"),
  	("Что думаешь о спорте?",
  		"Спорт — это здорово; помогает поддерживать форму."),
  	("Как ты относишься к животным?",
  		"Я люблю животных; у меня есть собака."),
  	("Ты любишь читать книги?",
  		"Да; особенно перед сном."),
    ("Привет","Привет"),
    ("Пливет","Добрый вечер"),
    ("приветик", "привет"),
    ("Привет", "добрый вечер"),
    ("Добрый день", "привет"),
    ("привет", "Здравствуй"),
    ("Здравствуй","привет"),
    ("Прив","Привет"),
    ("Плив","Добрый вечер"),
    ("Прив", "добрый вечер"),
    ("привет","здарова"),
    ("прив", "здарова")


]

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import tensorflow as tf

questions = []
answers = []

for question, answer in data:
  for z in['.',',','?','!']:
    question = question.replace(z,"")
    answer = answer.replace(z,"")
  questions.append(question.strip().lower())
  answers.append(answer.strip().lower())

print(questions,'\n',answers)

['в дис', 'влад ты сегодня работаешь', 'да думал может в дис', 'ну сейчас помоюсь еду погрею и буду', 'влад не хочешь в дис через 5 мин', 'пойдём играть', 'влад ты когда домой', 'а кто-то вчера вечером говорил покушает и спать', 'го в желике в бк работать может с той тянкой познакомишься', 'влад ты мне про давинчик написал и теперь он мне написывает мне страшно', 'а', 'ну хз', 'а что', 'что-нибудь придумаем', 'ну это тоже прикольно а может на сво', 'бля я бургеры вроде год не ел', 'я мясо блал', 'сука я ещё не завтракал сегодня сижу на паре как сыч', 'а', 'норм', 'да ты за ночь и дмс проходил', 'тут ещё чел ну как ты только волосы короче он 73 весит а ты вроде 85 или 80 как', 'прив', 'влад хочешь в дис', 'оооо у меня незачёт', 'я на соревнованиях второе место занял', 'торговаться будем', 'привет', 'нет человек-паук я не хотел(', 'очки кайф', 'думаю', 'взвешиваю все за и против', 'нескоро(', 'а я всю ночь просыпался чтобы опередить будильник потому что с громкостью тедефона какие-то мут

In [ ]:
tokenizer_q = Tokenizer()
tokenizer_q.fit_on_texts(questions)
tokenizer_a = Tokenizer()
tokenizer_a.fit_on_texts(answers)

sequences_q = tokenizer_q.texts_to_sequences(questions)
sequences_a = tokenizer_a.texts_to_sequences(answers)

max_length_q = int(max(len(seq) for seq in sequences_q))
max_length_a = int(max(len(seq) for seq in sequences_a))

X = pad_sequences(sequences_q, maxlen=max_length_q)
y = pad_sequences(sequences_a, maxlen=max_length_a)
print(X,'\n',y)
#

[[  0   0   0 ...   0   7 168]
 [  0   0   0 ...   1  26 201]
 [  0   0   0 ...  24   7 168]
 ...
 [  0   0   0 ...   0   0 186]
 [  0   0   0 ...   0   0  22]
 [  0   0   0 ...   0   0 186]] 
 [[  0   0   0 ...   0   0 242]
 [  0   0   0 ...  17   8 332]
 [  0   0   0 ...   0  11 242]
 ...
 [  0   0   0 ...   0 261 262]
 [  0   0   0 ...   0   0 386]
 [  0   0   0 ...   0   0 386]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding, TimeDistributed

vocab_size_q = len(tokenizer_q.word_index)+1
vocab_size_a = len(tokenizer_a.word_index)+1

model = Sequential()
model.add(Embedding(input_dim=vocab_size_q, output_dim=64, input_length=max_length_q))
model.add(tf.keras.layers.Bidirectional(LSTM(64, return_sequences=False)))
model.add(tf.keras.layers.Dropout(0.1))
model.add(tf.keras.layers.RepeatVector(max_length_a))
model.add(tf.keras.layers.Bidirectional(LSTM(64, return_sequences=True)))
model.add(tf.keras.layers.BatchNormalization())
model.add(TimeDistributed(Dense(vocab_size_a, activation='softmax')))
model.add(tf.keras.layers.Dropout(0.1))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

model.summary()
#

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional (Bidirectional)        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ repeat_vector (RepeatVector)         │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional_1 (Bidirectional)      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ ?                           │     0 (unbuilt) │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ time_distributed (TimeDistributed)   │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train, np.expand_dims(y_train, -1),
          validation_data=(X_test, y_test), epochs=120)
#

Epoch 1/120
19/19 ━━━━━━━━━━━━━━━━━━━━ 2s 129ms/step - accuracy: 0.2970 - loss: 6.4817 - val_accuracy: 0.7223 - val_loss: 4.3613
Epoch 2/120
19/19 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - accuracy: 0.5475 - loss: 4.7122 - val_accuracy: 0.7271 - val_loss: 2.8481
Epoch 3/120
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - accuracy: 0.5904 - loss: 3.9374 - val_accuracy: 0.7287 - val_loss: 2.3137
Epoch 4/120
19/19 ━━━━━━━━━━━━━━━━━━━━ 4s 140ms/step - accuracy: 0.6206 - loss: 3.3846 - val_accuracy: 0.7449 - val_loss: 1.8446
Epoch 5/120
19/19 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - accuracy: 0.6350 - loss: 3.0745 - val_accuracy: 0.7287 - val_loss: 1.8344
Epoch 6/120
19/19 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - accuracy: 0.6320 - loss: 2.8723 - val_accuracy: 0.7328 - val_loss: 1.6853
Epoch 7/120
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - accuracy: 0.6387 - loss: 2.7604 - val_accuracy: 0.7449 - val_loss: 1.5378
Epoch 8/120
19/19 ━━━━━━━━━━━━━━━━━━━━ 3s 77ms/step - accuracy: 0.6404 - loss: 2.5992 - val_accuracy: 

In [ ]:
def generate_answer(string):

  for z in ['.',',','?','!']:

    string = string.replace(z,"")
  string = string.lower()
  print(string)
  sequence = tokenizer_q.texts_to_sequences([string])
  padded_sequence = pad_sequences(sequence, maxlen=max_length_q)

  predicted_sequence = model.predict(padded_sequence)

  predicted_indices = np.argmax(predicted_sequence, axis=-1)
  for i in range(len(predicted_indices)):
    if (predicted_indices[0][i+1]==predicted_indices[0][i]):
      predicted_indices[0][i]=0
    elif(predicted_indices[0][i]==predicted_indices[0][i+1]):
      predicted_indices[0][i]=0
  print(predicted_indices)
  words = []
  for i in predicted_indices[0]:
    if i !=0:
      words.append(tokenizer_a.index_word[i])
  return ' '.join(words)
question_input = 'Привет'
answer_output = generate_answer(question_input)
print(answer_output)

привет
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 739ms/step
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9]]
что


In [ ]:
question_input = 'в дис?'
answer_output = generate_answer(question_input)
print(answer_output)

в дис
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  242]]
го


In [ ]:
while True:
  question_input = input()
  print(generate_answer(question_input))

привет
привет
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9]]
что
как дела?
как дела
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 44]]
как
ты тупой?
ты тупой
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  62  13 410
   86]]
еще на аву поставишь
что делаешь?
что делаешь
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  3 98 13 73]]
не не поверишь на заводе
пон\
пон\
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   3
  262]]
не вечер


KeyboardInterrupt: Interrupted by user